# Generated by Django 4.2.3 on 2023-07-30 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boatapp', '0002_boat_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название заказа')),
                ('email', models.EmailField(max_length=150, verbose_name='почта')),
                ('message', models.TextField(verbose_name='сообщение')),
                ('closed', models.BooleanField(default=False, verbose_name='заказ закрыт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boatapp.boat', verbose_name='лодка')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
